import { clientContainer } from "@/app/_interfaces";

export const BodyRowDataOfClientContainers: clientContainer[] = [
  {
    id: 1,
    wasteType: "Waste value1",
    status: "Full",
    volumeValue: "Danger",
    weightValue: "VeryDanger",
  },
  {
    id: 2,
    wasteType: "Waste value2",
    status: "Empty",
    volumeValue: "Safe",
    weightValue: "Medium",
  },
  {
    id: 3,
    wasteType: "Waste value3",
    status: "Half",
    volumeValue: "Moderate",
    weightValue: "Light",
  },
  {
    id: 4,
    wasteType: "Waste value4",
    status: "Full",
    volumeValue: "Critical",
    weightValue: "Heavy",
  },
  {
    id: 5,
    wasteType: "Waste value5",
    status: "Empty",
    volumeValue: "Safe",
    weightValue: "VeryLight",
  },
  {
    id: 6,
    wasteType: "Waste value6",
    status: "Half",
    volumeValue: "Moderate",
    weightValue: "Medium",
  },
  {
    id: 7,
    wasteType: "Waste value7",
    status: "Full",
    volumeValue: "Critical",
    weightValue: "VeryHeavy",
  },
  {
    id: 8,
    wasteType: "Waste value8",
    status: "Empty",
    volumeValue: "Safe",
    weightValue: "Light",
  },
  {
    id: 9,
    wasteType: "Waste value9",
    status: "Half",
    volumeValue: "Moderate",
    weightValue: "Heavy",
  },
  {
    id: 10,
    wasteType: "Waste value10",
    status: "Full",
    volumeValue: "Danger",
    weightValue: "VeryDanger",
  },
  {
    id: 11,
    wasteType: "Waste value11",
    status: "Empty",
    volumeValue: "Safe",
    weightValue: "VeryLight",
  },
  {
    id: 12,
    wasteType: "Waste value12",
    status: "Half",
    volumeValue: "Moderate",
    weightValue: "Medium",
  },
];
